set-option -g default-shell /bin/zsh
# for ubuntu:
# set -g default-terminal "tmux-256color"

# for mac:
set -g default-terminal "xterm-256color"

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# keybinds
# bind | split-window -h
# bind - split-window -v
# unbind '"'
# unbind %

# scrollback buffer
set-option -g history-limit 10000
