#!/bin/bash

# brew packages to install
# amethyst
# fzf
# nvim exa hugo
# bash-completion@2

# create directories
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"/bash
mkdir -p "$XDG_CONFIG_HOME"/alacritty
mkdir -p "$XDG_CONFIG_HOME"/skhd

# git clone https://github.com/magicmonty/bash-git-prompt.git "$XDG_CONFIG_HOME"/bash/.bash-git-prompt --depth=1

# Symbolic links

# ln -s ./.amethyst.yml "$HOME"/.amethyst.yml
ln -sf "$PWD/alacritty.yml" "$XDG_CONFIG_HOME"/alacritty/alacritty.yml
ln -sf "$PWD/.bash_profile" "$HOME"/.bash_profile
ln -sf "$PWD/.bashrc" "$HOME"/.bashrc
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/skhdrc" "$XDG_CONFIG_HOME"/skhd/skhdrc

# set up blog
# git clone git@github.com:mischavandenburg/hugo-PaperModX-theme.git themes/PaperModX --depth=1
