#!/bin/bash

# syncs public zettels to Quartz repo and publishes them

SOURCE_DIR='/Users/mischa/Library/Mobile Documents/iCloud~md~obsidian/Documents/The Garden/Zettelkasten/zp'
DEST_DIR="/Users/mischa/Repos/github.com/jackyzha0/quartz/content"

# Use rsync to sync the folders
rsync -av "$SOURCE_DIR/" "$DEST_DIR"

cd /Users/mischa/Repos/github.com/jackyzha0/quartz || exit
git add .
git commit -m "Automated commit at $(date)"
git push
