#!/bin/bash

gsed -i 's/size = 25/size = 38/g' /users/mischa/repos/github.com/mischavandenburg/dotfiles/alacritty.toml

cat <<EOF
Recording checklist:
- Check if microphone is on
- Turn on Keycastr - ctrl opt cmd K
- Verify if recording proper screen
EOF
