#!/bin/bash

# execute sed command on every file in the directory recursively

# old='\"editable\": false'
# new='\"editable\": true'
old='#video'
new='#Video'

# yaml
# find . -type f -name "*.yaml" -exec gsed -i "s/$old/$new/g" {} \;

# json
# find . -type f -name "*.json" -exec gsed -i "s/$old/$new/g" {} \;

# jsonc
# find . -type f -name "*.jsonc" -exec gsed -i "s/$old/$new/g" {} \;

#markdown
find . -type f -name "*.md" -exec gsed -i "s/$old/$new/g" {} \;

# EVERYTHING
# find . -type f -exec gsed -i "s/$old/$new/g" {} \;
