#!/bin/bash

# execute sed command on every file in the directory recursively

old='daysAfterCreationGreaterThan": 1'
new='daysAfterCreationGreaterThan": 7'

# yml
# find . -type f -name "*.yml" -exec gsed -i "s/$old/$new/g" {} \;

# jsonc
find . -type f -name "*.jsonc" -exec gsed -i "s/$old/$new/g" {} \;
