#!/bin/bash

# execute sed command on every file in the directory recursively

old='mealie'
new='linkding'

# yml
find . -type f -name "*.yaml" -exec gsed -i "s/$old/$new/g" {} \;

# jsonc
# find . -type f -name "*.jsonc" -exec gsed -i "s/$old/$new/g" {} \;
