#!/bin/bash

# TODO set up daily template
# Maybe just copy a template file and sed the dates?

cd "$SECOND_BRAIN" || exit

# Open the daily note at the bottom of the file in insert mode and run NoNeckPain to make it center
nvim '+ normal Go' "$SECOND_BRAIN""/periodic notes/daily notes/$(date +"%Y-%m-%d").md" -c :NoNeckPain
