#!/bin/bash

# for debugging:
# set -exo pipefail

# stop the script if an error occurs
set -e

# get the do not disturb status
STATUS=$(defaults read com.apple.controlcenter "NSStatusItem Visible FocusModes")

if [[ $STATUS -eq 1 ]]; then
	echo "Do Not Disturb is turned On."
else
	echo "Do Not Disturb is turned Off."
fi

# echo "$STATUS"
