#!/bin/bash

gsed -i 's/size = 25/size = 35/g' /Users/mischa/Repos/github.com/mischavandenburg/dotfiles/alacritty.toml

cat <<EOF
Recording checklist:
- Check if microphone is on
- Turn on Keycastr
- Verify if recording proper screen
EOF
