#!/bin/bash

# A bash script that helps me create notes in my second brain
# based on my "blog" script
# TODO
# 1. check if file already exists
# 2. write this in Go :)
# 3. take filename as argument and prompt if empty
# 4.

# Define a function to prompt the user for a filename
get_filename() {
	read -p "Enter a filename: " filename
}

# Define a function to create and open a file in the specified directory
open_file() {

	# Cd into the directory
	cd "$1" || exit
	# Create the file in the specified directory
	touch "$1/$filename.md"

	# format the file
	# create unique identifier and links section

	timestamp="$(date +"%Y%m%d%H%m")"

	echo "# " >>"$1/$filename.md"
	echo -en "\n" >>"$1/$filename.md"
	echo -en "\n" >>"$1/$filename.md"
	echo -en "\n" >>"$1/$filename.md"
	echo "Links:" >>"$1/$filename.md"
	echo -en "\n" >>"$1/$filename.md"
	echo "$timestamp" >>"$1/$filename.md"

	# Open the file in Neovim
	nvim '+ normal ggzzi' "$1/$filename.md" -c :NoNeckPain
}

# Prompt the user if no filename is provided
if [[ $# -eq 0 ]]; then
	get_filename
fi

# set filename to the argument given to the script
filename=$1
open_file "$SECOND_BRAIN/0-inbox"
